version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - DEBUG=0
    command: /start.sh

volumes:
  static_volume:
