# Generated by Django 3.0 on 2024-05-06 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations


def migrate_data(apps, schema_editor):
    OldLetting = apps.get_model("oc_lettings_site", "Letting")
    OldAddress = apps.get_model("oc_lettings_site", "Address")
    OldProfile = apps.get_model("oc_lettings_site", "Profile")

    Letting = apps.get_model("lettings", "Letting")
    Address = apps.get_model("lettings", "Address")
    Profile = apps.get_model("profiles", "Profile")
    
    old_profiles = OldProfile.objects.all()
    for old_profile in old_profiles:
        new_profile = Profile(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city,
        )
        new_profile.save()

    old_adresses = OldAddress.objects.all()
    for old_adress in old_adresses:
        
        new_adress = Address(
            number=old_adress.number,
            street=old_adress.street,
            city=old_adress.city,
            state=old_adress.state, 
            country_iso_code=old_adress.country_iso_code,      
        )
        new_adress.save()

    old_lettings = OldLetting.objects.all()
    for old_letting in old_lettings:
        address = Address.objects.filter(
            number=old_letting.address.number,
            street=old_letting.address.street,
            city=old_letting.address.city,
            state=old_letting.address.state,
            zip_code=old_letting.address.zip_code,
            country_iso_code=old_letting.address.country_iso_code,
            ).first()
        new_letting = Letting(
            title=old_letting.title,
            address=address,
        )
        new_letting.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oc_lettings_site', '0001_initial'),
        ('profiles', '0001_initial'), 
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_data),
    ]
